### ISSUE TITLE
upgrade to 2.0.1 then "customizer is not a function"

### ISSUE THREAD

**Issue by astik** [mgol/grunt-ng-annotate#48]
Hi,

Just upgrade my current project to 2.0.1 :

```
"grunt-ng-annotate": "2.0.1"
```

After "npm install" :

```
├─┬ grunt-contrib-concat@1.0.0
│ └── source-map@0.5.3 
├─┬ grunt-contrib-uglify@1.0.0
│ └─┬ uglify-js@2.6.2
│   └── source-map@0.5.3 
├─┬ grunt-jscs@2.8.0
│ └─┬ jscs@2.11.0
│   └─┬ babel-jscs@2.0.5
│     └─┬ babel-core@5.8.35
│       ├─┬ regenerator@0.8.40
│       │ └─┬ recast@0.10.33
│       │   └── source-map@0.5.3 
│       └── source-map@0.5.3 
└─┬ grunt-ng-annotate@2.0.1 
  ├── lodash.clonedeep@4.3.1 
  └─┬ ng-annotate@1.2.1 
    ├── acorn@2.6.4 
    ├─┬ optimist@0.6.1 
    │ └── minimist@0.0.10 
    ├─┬ ordered-ast-traverse@1.1.1 
    │ └── ordered-esprima-props@1.1.0 
    └── source-map@0.5.3 
```

Here is my Grunt conf :

```
		ngAnnotate : {
			appJs : {
				files : [ {
					expand : true,
					cwd : '<%= yeoman.tmp %>/scripts',
					src : [ 'app.js' ],
					dest : '<%= yeoman.tmp %>/scripts'
				} ]
			}
		}
```

Here is the result for the CLI "grunt ngAnnotate:appJs --debug --verbose" :

```
Running tasks: ngAnnotate:appJs

Running "ngAnnotate:appJs" (ngAnnotate) task
[D] Task source: /Volumes/chine/mfg_WECHAT_POC/node_modules/grunt-ng-annotate/tasks/ng-annotate.js
Verifying property ngAnnotate.appJs exists in config...OK
Files: .tmp/scripts/app.js -> .tmp/scripts/app.js
Options: (none)
Warning: customizer is not a function Use --force to continue.

Aborted due to warnings.
```

Also, I'm working on node 5.3.0 :

```
# node -v
v5.3.0
```

It was working perfectly with "1.0.1".

**Comment by mgol** [comment]
Could you run Grunt with flags --debug --verbose --stack, create a gist
with the output (it will be much longer) at gist.github.com and link to it
here? Thanks!

-- 
Michał Gołębiowski

**Comment by mgol** [comment]
There were no significant changes in the code of `grunt-ng-annotate` 1.0.1 & 2.0.1 (it was mostly build/test stuff) so I'm not sure what could have broken for you...

Once you generate the log wit the flags described above, please remove `node_modules`, change the `grunt-ng-annotate` dependency back to 1.0.1 and please check again if there are no problems.

Also, just in case, could you update your Node to the latest 5.8.0 and see if it's still a problem?

**Comment by astik** [comment]
After removing the node_modules folder and "npm install" again, no more issue ... As I havent list dependencies before purging my folder, I don't know what dependency cause the incompatibility.
I have made a diff between dependency list with version 1.0.1 and 2.0.1. The only difference is with Lodash dependencies. So my guess is that I had an old version on my project and cleaning the node_modules folder fix the issue.
Anyway, thanks for the advice, now everything is running well =)

**Comment by mgol** [comment]
Thanks for the update!

-- 
Michał Gołębiowski
